alias ls='ls --color=auto'
alias ll='ls -laF'
alias lock='vlock -a'
alias gcc='gcc -Wall -Werror -pedantic -std=gnu99'
alias clang='clang -Wall -Werror -pedantic -std=gnu99'
alias tspeak='/home/synthverity/workspace/TeamSpeak3-Client-linux_amd64/ts3client_runscript.sh'
alias vi='vim'
