highlight cComment ctermfg=darkcyan guifg=darkcyan
highlight cConstant ctermfg=darkred guifg=darkred
highlight cStatement ctermfg=darkmagenta guifg=darkmagenta
highlight cConditional ctermfg=yellow guifg=yellow
highlight cRepeat ctermfg=yellow guifg=yellow
highlight cNumber ctermfg=white guifg=white
highlight cType ctermfg=darkgreen guifg=darkgreen
highlight cString ctermfg=lightgreen guifg=lightgreen
highlight cSpecial ctermfg=lightgreen guifg=lightgreen
